# Generated by Django 4.1.6 on 2023-02-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of Item', max_length=200)),
                ('description', models.CharField(help_text='Enter description', max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
